---
- hosts: workstation

  tasks:
    - name: install iterm2
      mac_pkg: pkg_type=app
               url=https://iterm2.com/downloads/stable/iTerm2_v2_0.zip
               archive_type=zip archive_path=iTerm.app
      sudo: yes

    - name: download themes
      get_url: url= {{item.src}}
               dest=/tmp/{{item.dest}}
      with_items:
        - src: https://github.com/mbadolato/iTerm2-Color-Schemes/tarball/master
          dest: iTerm2-Color-Schemes.tar.gz
        - src: https://github.com/zenorocha/dracula-theme/archive/master.zip
          dest: dracula-theme.tar.gz
        - src: 
    - name: unzip themes
      unarchive: copy=no dest=/tmp/iTerm2-Color-Schemes
                 src=/tmp/iTerm2-Color-Schemes.tar.gz

    - name: install themes
