---
- hosts: workstation

  tasks:
    - name: get powerline-shell script
      git: repo=https://github.com/milkbikis/powerline-shell
           dest=/opt/powerline-shell

    - name: Create basic config file
      command: cp /opt/powerline-shell/config.py.dist /opt/powerline-shell/config.py

    - name: install powerline-shell
      command: /opt/powerline-shell/install.py
    
    - name: link symbolic file
      file: src={{item.from}} dest={{item.to}} state=link
      sudo: no
      with_items:
         - from: /opt/powerline-shell/powerline-shell.py
           to: /opt/bin/powerline-shell.py

# git clone https://github.com/milkbikis/powerline-shell
# cd powerline-shell
# cp config.py.dist config.py
# ./install.py
# ln -s <path/to/powerline-shell.py> ~/bin/powerline-shell.py

