---
- hosts: workstation

  tasks:
    - name: get powerline-shell script
      git: repo=https://github.com/milkbikis/powerline-shell
           dest=/opt/powerline-shell

    - name: Create basic config file
      command: cp /opt/powerline-shell/config.py.dist /opt/powerline-shell/config.py

    - name: install powerline-shell
      command: /opt/powerline-shell/install.py
      args:
        chdir: /opt/powerline-shell/
        creates: /opt/powerline-shell/powerline-shell.py

    - name: make script executible
      file: path=/opt/powerline-shell/powerline-shell.py state=file mode=755
    
    - name: make /opt/bin
      file: path=/opt/bin state=directory

    - name: link symbolic file
      file: src={{item.from}} dest={{item.to}} state=link
      with_items:
        - from: /opt/powerline-shell/powerline-shell.py
          to: /opt/bin/powerline-shell.py

