---
- hosts: workstation

  tasks:
    - name: install virtualbox
      mac_pkg: pkg_name=org.virtualbox.pkg.virtualbox pkg_version=4.3.26
               url=http://download.virtualbox.org/virtualbox/4.3.26/VirtualBox-4.3.26-98988-OSX.dmg
               archive_type=dmg archive_path=VirtualBox.pkg
      sudo: yes

