---
- hosts: workstation

  tasks:
    - name: install Viscosity
      mac_pkg: pkg_type=app
               url=http://swupdate.sparklabs.com/download/mac/release/viscosity/Viscosity%201.5.6.dmg
               archive_type=dmg archive_path='Viscosity.app'
      sudo: yes
